/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/election/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the unified election simulation */
        post: operations["simulateElection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/election/combined-effects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 2x2x2 factorial: how each model (blank/campaign/info) shifts the result */
        post: operations["combinedEffects"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/election/campaign-sensitivity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snapshot the election at multiple campaign days */
        post: operations["campaignSensitivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/election/abstention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iterated abstention model with poll feedback */
        post: operations["abstention"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/election/coalition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** D'Hondt seat allocation + greedy coalition formation */
        post: operations["coalition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BlankVoteConfig
         * @description Constitutional blank-vote rule + optional contagion.
         */
        BlankVoteConfig: {
            /**
             * Enabled
             * @description Apply the constitutional rule to the winner.
             * @default false
             */
            enabled: boolean;
            /**
             * Rule
             * @description 'symbolic' | 'competitive' | 'threshold_30'.
             * @default symbolic
             */
            rule: string;
            contagion?: components["schemas"]["ContagionConfig"];
        };
        /**
         * CampaignConfig
         * @description Polling-bandwagon dynamics over a few days.
         */
        CampaignConfig: {
            /**
             * Enabled
             * @description Apply campaign dynamics to true utilities.
             * @default false
             */
            enabled: boolean;
            /**
             * Num Days
             * @description Campaign length in days.
             * @default 30
             */
            num_days: number;
            /**
             * Polling Effect
             * @description 0 = ignore polls, 1 = ballots follow polls.
             * @default 0.3
             */
            polling_effect: number;
        };
        /**
         * CandidateSpec
         * @description A single candidate placed at a 2D ideological position on [-1, 1]².
         */
        CandidateSpec: {
            /**
             * Name
             * @description Candidate display name.
             */
            name: string;
            /**
             * X
             * @description Economy axis. -1 = far left, +1 = far right.
             */
            x: number;
            /**
             * Y
             * @description Social axis. -1 = liberal, +1 = conservative.
             */
            y: number;
        };
        /**
         * ContagionConfig
         * @description SIS-style blank-vote contagion parameters.
         */
        ContagionConfig: {
            /**
             * Enabled
             * @description Whether contagion is applied.
             * @default false
             */
            enabled: boolean;
            /**
             * Beta
             * @description Infection rate β (probability of converting per neighbour).
             * @default 0.15
             */
            beta: number;
            /**
             * Gamma
             * @description Recovery rate γ.
             * @default 0.1
             */
            gamma: number;
            /**
             * Network
             * @description Network topology: 'random' | 'watts_strogatz' | 'block'.
             * @default random
             */
            network: string;
        };
        /**
         * InformationModelConfig
         * @description Media bias × voter information level adjustment of perceived utilities.
         */
        InformationModelConfig: {
            /**
             * Enabled
             * @description Apply information asymmetry.
             * @default false
             */
            enabled: boolean;
            /**
             * Media Bias
             * @description Per-candidate media bias [-1, +1].
             */
            media_bias?: {
                [key: string]: number;
            };
            /**
             * Voter Segments
             * @description Share of voters in each information bucket. Sums should be ~1.
             */
            voter_segments?: {
                [key: string]: number;
            };
        };
        /**
         * SimulateRequest
         * @description POST /api/election/simulate — full pipeline run.
         */
        SimulateRequest: {
            /**
             * Candidates
             * @description 2 to 8 candidates. Beyond that, Kemeny-Young falls back to KwikSort approximation.
             */
            candidates: components["schemas"]["CandidateSpec"][];
            /**
             * Num Voters
             * @default 300
             */
            num_voters: number;
            /**
             * Ideology
             * @description Voter distribution: 'random' | 'centrist' | 'polarized' | 'left_skewed' | 'right_skewed'.
             * @default random
             */
            ideology: string;
            /**
             * Seed
             * @description PRNG seed for reproducibility.
             * @default 42
             */
            seed: number;
            blank_vote?: components["schemas"]["BlankVoteConfig"];
            information_model?: components["schemas"]["InformationModelConfig"];
            campaign?: components["schemas"]["CampaignConfig"];
        };
        /**
         * CandidateSnapshot
         * @description Candidate as returned in /simulate (with derived party label).
         */
        CandidateSnapshot: {
            /** Name */
            name: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Party */
            party: string;
        };
        /**
         * MethodResult
         * @description Result of a single voting method on one electorate.
         */
        MethodResult: {
            /**
             * Winner
             * @description Method winner.
             * @default null
             */
            winner: string | null;
            /**
             * Bayesian Regret
             * @description Lower = better welfare.
             * @default null
             */
            bayesian_regret: number | null;
            /**
             * Majority Satisfaction
             * @description Share of voters satisfied (0..1).
             * @default null
             */
            majority_satisfaction: number | null;
            /**
             * Condorcet Consistent
             * @description Did the method elect the Condorcet winner?
             * @default null
             */
            condorcet_consistent: boolean | null;
            /**
             * Winner With Blank
             * @description Winner after blank-vote rule (if enabled).
             * @default null
             */
            winner_with_blank: string | null;
            /**
             * Blank Triggered
             * @description Did the blank-vote rule fire?
             * @default null
             */
            blank_triggered: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * VoterSnapshot
         * @description One voter row in the ideology map.
         */
        VoterSnapshot: {
            /** Id */
            id: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Blank Threshold Final */
            blank_threshold_final: number;
        };
        /**
         * SimulateResponse
         * @description Result of /simulate — keys read by LabCentralView, IdeologyMap, MethodMatrix.
         */
        SimulateResponse: {
            /**
             * Config
             * @description Echo of the original request.
             */
            config: {
                [key: string]: unknown;
            };
            /** Voters Snapshot */
            voters_snapshot: components["schemas"]["VoterSnapshot"][];
            /** Candidates */
            candidates: components["schemas"]["CandidateSnapshot"][];
            /**
             * Methods
             * @description Keyed by method slug.
             */
            methods: {
                [key: string]: components["schemas"]["MethodResult"];
            };
            /**
             * Condorcet Winner
             * @default null
             */
            condorcet_winner: string | null;
            /** Blank Rate */
            blank_rate: number;
            /**
             * Campaign Trajectory
             * @default null
             */
            campaign_trajectory: {
                [key: string]: unknown;
            } | null;
            /** Inter Method Agreement */
            inter_method_agreement: number;
            /** Condorcet Exists */
            condorcet_exists: boolean;
        };
        /**
         * CombinedEffectsRequest
         * @description Same shape as SimulateRequest but with a tighter num_voters cap (2³=8 simulations).
         */
        CombinedEffectsRequest: {
            /** Candidates */
            candidates: components["schemas"]["CandidateSpec"][];
            /**
             * Num Voters
             * @default 150
             */
            num_voters: number;
            /**
             * Ideology
             * @default random
             */
            ideology: string;
            /**
             * Seed
             * @default 42
             */
            seed: number;
            blank_vote?: components["schemas"]["BlankVoteConfig"];
            information_model?: components["schemas"]["InformationModelConfig"];
            campaign?: components["schemas"]["CampaignConfig"];
        };
        /** CombinedEffectsCombination */
        CombinedEffectsCombination: {
            /** Id */
            id: string;
            /** Blank */
            blank: boolean;
            /** Campaign */
            campaign: boolean;
            /** Information Model */
            information_model: boolean;
            /** Plurality Winner */
            plurality_winner: string | null;
            /** Condorcet Winner */
            condorcet_winner: string | null;
            /** Inter Method Agreement */
            inter_method_agreement: number;
            /** Winner Differs From Base */
            winner_differs_from_base: boolean;
        };
        /** CombinedEffectsResponse */
        CombinedEffectsResponse: {
            /** Base Winner */
            base_winner: string | null;
            /** Combinations */
            combinations: components["schemas"]["CombinedEffectsCombination"][];
            /**
             * Factor Deltas
             * @description Agreement delta per factor (in %). Negative = factor disrupts agreement.
             */
            factor_deltas: {
                [key: string]: number;
            };
            /** Most Disruptive Factor */
            most_disruptive_factor: string;
            /** Least Disruptive Factor */
            least_disruptive_factor: string;
            /** Max Disruption Combination */
            max_disruption_combination: string;
        };
        /** CampaignSensitivityRequest */
        CampaignSensitivityRequest: {
            /** Candidates */
            candidates: components["schemas"]["CandidateSpec"][];
            /**
             * Num Voters
             * @default 150
             */
            num_voters: number;
            /**
             * Ideology
             * @default random
             */
            ideology: string;
            /**
             * Seed
             * @default 42
             */
            seed: number;
            /**
             * Snapshot Days
             * @description Days at which to snapshot — strings ('final') and ints are both accepted.
             */
            snapshot_days?: unknown[];
            blank_vote?: components["schemas"]["BlankVoteConfig"];
            campaign?: components["schemas"]["CampaignConfig"];
        };
        /** CampaignSnapshot */
        CampaignSnapshot: {
            /** Day */
            day: unknown;
            /** Methods */
            methods: {
                [key: string]: components["schemas"]["MethodResult"];
            };
            /** Condorcet Winner */
            condorcet_winner: string | null;
        } & {
            [key: string]: unknown;
        };
        /** CampaignSensitivityResponse */
        CampaignSensitivityResponse: {
            /** Snapshots */
            snapshots: components["schemas"]["CampaignSnapshot"][];
            /**
             * Method Stability
             * @description Per-method: winner_changes count, final_winner, stability_score [0..1].
             */
            method_stability: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Most Stable Method */
            most_stable_method: string | null;
            /** Least Stable Method */
            least_stable_method: string | null;
        };
        /** AbstentionRequest */
        AbstentionRequest: {
            /** Candidates */
            candidates: components["schemas"]["CandidateSpec"][];
            /**
             * Num Voters
             * @default 200
             */
            num_voters: number;
            /**
             * Ideology
             * @default random
             */
            ideology: string;
            /**
             * Seed
             * @default 42
             */
            seed: number;
            /**
             * Demobilization Factor
             * @description 0 = no abstention, 1 = aggressive demobilisation.
             * @default 0.5
             */
            demobilization_factor: number;
            /**
             * Poll Influence
             * @description How much polls affect abstention probability.
             * @default 0.8
             */
            poll_influence: number;
            /**
             * Num Rounds
             * @default 3
             */
            num_rounds: number;
        };
        /** AbstentionRound */
        AbstentionRound: {
            /** Round */
            round: number;
            /** Turnout */
            turnout: number;
            /** Vote Shares */
            vote_shares: {
                [key: string]: number;
            };
            /** Winner Fptp */
            winner_fptp: string | null;
            /** Winner Condorcet */
            winner_condorcet: string | null;
            /** Abstention Map */
            abstention_map: components["schemas"]["AbstentionVoter"][];
        } & {
            [key: string]: unknown;
        };
        /** AbstentionVoter */
        AbstentionVoter: {
            /** Id */
            id: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Preferred */
            preferred: string;
            /** Abstained */
            abstained: boolean;
            /** Prob Abstention */
            prob_abstention: number;
        };
        /** AbstentionResponse */
        AbstentionResponse: {
            /** Rounds */
            rounds: components["schemas"]["AbstentionRound"][];
            /** Sincere Winner */
            sincere_winner: string | null;
            /** Final Winner */
            final_winner: string | null;
            /** Winner Changed */
            winner_changed: boolean;
            /** Turnout By Camp */
            turnout_by_camp: {
                [key: string]: number;
            };
            /** Candidates */
            candidates: {
                [key: string]: unknown;
            }[];
            /**
             * Winners By Method
             * @default null
             */
            winners_by_method: {
                [key: string]: string | null;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** CoalitionRequest */
        CoalitionRequest: {
            /** Candidates */
            candidates: components["schemas"]["CandidateSpec"][];
            /**
             * Num Voters
             * @default 300
             */
            num_voters: number;
            /**
             * Ideology
             * @default random
             */
            ideology: string;
            /**
             * Seed
             * @default 42
             */
            seed: number;
            /**
             * Total Seats
             * @default 100
             */
            total_seats: number;
            /**
             * Threshold Pct
             * @description Electoral threshold (5 % default).
             * @default 0.05
             */
            threshold_pct: number;
        };
        /** Coalition */
        Coalition: {
            /** Members */
            members: string[];
            /** Total Seats */
            total_seats: number;
            /** Has Majority */
            has_majority: boolean;
        };
        /** SeatAllocation */
        SeatAllocation: {
            /** Candidate */
            candidate: string;
            /** Seats */
            seats: number;
            /** Pct */
            pct: number;
        };
        /** CoalitionResponse */
        CoalitionResponse: {
            /** Allocations */
            allocations: components["schemas"]["SeatAllocation"][];
            /** Majority Threshold */
            majority_threshold: number;
            formed_coalition: components["schemas"]["Coalition"] | null;
            /** @default null */
            runner_up_coalition: components["schemas"]["Coalition"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    simulateElection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    combinedEffects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CombinedEffectsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CombinedEffectsResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    campaignSensitivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignSensitivityRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignSensitivityResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    abstention: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbstentionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbstentionResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    coalition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoalitionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoalitionResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
