"""Shared pieces of the Claude Code guardrail hooks (CI hardening plan, phase 4).

Each hook reads the tool payload on stdin and prints at most one JSON decision.
These guards limit what an agent session can do on its own: they are not a
security boundary against a determined attacker (CI and the Mergify review hold
are), but they turn the repo's written rules into checks that actually run.
"""
from __future__ import annotations

import json
import re
import shlex
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]

# Files that make up the safety net: editing one weakens a gate or a guard, so
# the owner confirms it. Kept close to .mergify.yml's review-hold list, minus the
# engine and test code an agent is expected to edit in normal work.
GUARDRAIL_PATTERNS = [
    r"^\.github/workflows/",
    r"^\.mergify\.yml$",
    r"^\.claude/settings[^/]*\.json$",
    r"^\.claude/hooks/",
    r"^scripts/(check_|fast-gate\.sh$|setup-branch-protection\.sh$)",
    r"^voter-app/scripts/check-",
    r"^\.github/[^/]*(baseline|snoozes|allowlist)[^/]*\.json$",
    r"^\.(gitleaks\.toml|gitleaksignore|trivyignore\.yaml|semgrepignore|secrets\.baseline|jscpd\.json)$",
    r"^\.semgrep/",
    r"^fast_api_voter/(pyproject\.toml|mypy\.ini|\.vulture_whitelist\.py)$",
    r"^voter-app/(vitest\.config\.ts|stryker\.config\.json|eslint\.config\.js|\.dependency-cruiser\.json"
    r"|\.size-limit\.json|tsconfig[^/]*\.json|knip\.json|playwright[^/]*\.config\.ts)$",
    # Oracles regenerated by scripts: a hand edit is never right.
    r"^fast_api_voter/api/tests/golden/",
    r"(^|/)__snapshots__/",
    r"-snapshots/",
]
_GUARDRAIL_RE = [re.compile(p) for p in GUARDRAIL_PATTERNS]


def read_payload() -> dict[str, Any]:
    try:
        data = json.load(sys.stdin)
    except Exception:  # noqa: BLE001 -- a hook must never crash the session on bad input
        return {}
    return data if isinstance(data, dict) else {}


def rel_path(path: str) -> str:
    """Repo-relative, forward-slash path ('' when outside the repo)."""
    if not path:
        return ""
    p = Path(path.replace("\\", "/"))
    if p.is_absolute():
        try:
            p = p.resolve().relative_to(ROOT)
        except ValueError:
            return ""
    s = p.as_posix()
    return s[2:] if s.startswith("./") else s


def is_guardrail(rel: str) -> bool:
    return any(r.search(rel) for r in _GUARDRAIL_RE)


def decide(decision: str, reason: str, event: str = "PreToolUse") -> None:
    print(json.dumps({"hookSpecificOutput": {
        "hookEventName": event,
        "permissionDecision": decision,
        "permissionDecisionReason": reason,
    }}))


def context(text: str, event: str = "PreToolUse") -> None:
    print(json.dumps({"hookSpecificOutput": {"hookEventName": event, "additionalContext": text}}))


_SEPARATORS = re.compile(r"\s*(?:&&|\|\||;|\||\n)\s*")
_HEREDOC = re.compile(r"<<-?\s*(['\"]?)([A-Za-z_][A-Za-z0-9_]*)\1")


def strip_heredocs(command: str) -> str:
    """Drop heredoc bodies: they are data fed to a command (a file being
    written, a script piped to python), not commands themselves."""
    lines = (command or "").split("\n")
    out, i = [], 0
    while i < len(lines):
        line = lines[i]
        out.append(line)
        delims = [m.group(2) for m in _HEREDOC.finditer(line)]
        i += 1
        for delim in delims:
            while i < len(lines) and lines[i].strip() != delim:
                i += 1
            i += 1  # the delimiter line itself
    return "\n".join(out)


def shell_segments(command: str) -> list[list[str]]:
    """Split a shell command into simple commands, each as argv (best effort:
    heredoc bodies are ignored; unparseable segments fall back to whitespace
    splitting)."""
    out = []
    for seg in _SEPARATORS.split(strip_heredocs(command)):
        if not seg.strip():
            continue
        try:
            argv = shlex.split(seg)
        except ValueError:
            argv = seg.split()
        # Drop leading VAR=value assignments and common wrappers.
        while argv and (re.match(r"^[A-Za-z_][A-Za-z0-9_]*=", argv[0]) or argv[0] in {"sudo", "env", "command", "time", "nohup"}):
            argv = argv[1:]
        if argv:
            out.append(argv)
    return out
