"""Create election_voter table

Revision ID: 315647555aa9
Revises: 0d35ad8183fe
Create Date: 2025-03-27 19:25:58.226049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '315647555aa9'
down_revision: Union[str, None] = '0d35ad8183fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election_candidate',
                    sa.Column('election_id', sa.Integer(), nullable=False),
                    sa.Column('candidate_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['candidate_id'],
                                            ['candidates.id'], ),
                    sa.ForeignKeyConstraint(['election_id'],
                                            ['elections.id'], ),
                    sa.PrimaryKeyConstraint('election_id', 'candidate_id')
                    )
    op.create_table('election_voter',
                    sa.Column('election_id', sa.Integer(), nullable=False),
                    sa.Column('voter_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['election_id'],
                                            ['elections.id'], ),
                    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('election_id', 'voter_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('election_voter')
    op.drop_table('election_candidate')
    # ### end Alembic commands ###
