"""Initial migration

Revision ID: 4ee4e7c3064f
Revises:
Create Date: 2025-03-24 21:48:57.420141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision: str = '4ee4e7c3064f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name, connection):
    inspector = Inspector.from_engine(connection)
    return inspector.has_table(table_name)


def upgrade() -> None:
    connection = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(length=255),
                              nullable=True),
                    sa.Column('created_by', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if table_exists('result', connection):
        op.drop_table('result')
    if table_exists('vote', connection):
        op.drop_table('vote')

    # Check if the voter table exists before dropping it
    if table_exists('voter', connection):
        op.drop_table('voter')

    op.drop_table('user')
    op.drop_table('candidate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
                    sa.Column('id', sa.INTEGER(), autoincrement=True,
                              nullable=False),
                    sa.Column('voter_id', sa.INTEGER(), autoincrement=False,
                              nullable=False),
                    sa.Column('candidate_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('vote_type', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('rank', sa.INTEGER(), autoincrement=False,
                              nullable=True),
                    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=True),
                    sa.Column('rating', sa.INTEGER(), autoincrement=False,
                              nullable=True),
                    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'],
                                            name='vote_candidate_id_fkey'),
                    sa.ForeignKeyConstraint(['voter_id'], ['voter.id'],
                                            name='vote_voter_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='vote_pkey')
                    )
    op.create_table('candidate',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        "nextval('candidate_id_seq'::regclass)"),
                        autoincrement=True, nullable=False),
                    sa.Column('first_name', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.Column('last_name', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='candidate_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('result',
                    sa.Column('id', sa.INTEGER(), autoincrement=True,
                              nullable=False),
                    sa.Column('candidate_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('vote_count', sa.INTEGER(), autoincrement=False,
                              nullable=False),
                    sa.Column('vote_type', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['candidate_id'],
                                            ['candidate.id'],
                                            name='result_candidate_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='result_pkey')
                    )
    op.create_table('voter',
                    sa.Column('id', sa.INTEGER(), autoincrement=True,
                              nullable=False),
                    sa.Column('first_name', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.Column('last_name', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='voter_pkey')
                    )
    op.create_table('user',
                    sa.Column('id', sa.INTEGER(), autoincrement=True,
                              nullable=False),
                    sa.Column('username', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('password_hash', sa.VARCHAR(length=128),
                              autoincrement=False, nullable=False),
                    sa.Column('role', sa.VARCHAR(length=10),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='user_pkey'),
                    sa.UniqueConstraint('username', name='user_username_key')
                    )
    op.drop_table('elections')
    # ### end Alembic commands ###
