"""OBS-042's turnout cost: ADR-011's four facts under the rule that compares a voter's best candidate
with the blank ballot, on the same twin as calibrate_utility_vote.py.

Not pre-registered: the grid and the order below were chosen after OBS-042 found the old rule (best
against next best) growing with the field. It keeps ADR-011's facts and its selection order (least
partisanship + approval, then turnout nearest 67.5%) and adds two things: the cost grid, which runs
past the old one's 0.04 because the new rule keeps fewer voters home at any cost, and the reference
row, the old rule at 0.04 under each setting. The settings are the two the LLM path runs:
approval 0 (`_flagship_config`) and approval 0.1 (`_exploration_config`), both with partisanship 0.

Usage (from fast_api_voter/):
    python scripts/calibrate_turnout_rule.py      # writes calibrate_turnout_rule_results.md
"""
from __future__ import annotations

import collections
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import api.domain.polity.simple_rules as simple_rules  # noqa: E402
from api.domain.polity.citizen import Citizen  # noqa: E402
from api.domain.polity.twin_calibration import Arm, select, utility_vote_arm, utility_vote_choice  # noqa: E402
from calibrate_utility_vote import YEARS, ZERO, measure  # noqa: E402
from twin_runs import SEEDS, recording, run_twin, twin_config  # noqa: E402

COSTS = (0.04, 0.06, 0.08, 0.10, 0.12, 0.15, 0.20)
SETTINGS = ({"partisanship": 0.0, "approval": 0.0}, {"partisanship": 0.0, "approval": 0.1})
CARRYOVER = 0.5
RESULTS = Path(__file__).resolve().parent / "calibrate_turnout_rule_results.md"


def best_vs_next(voter: Citizen, utilities: Sequence[float], turnout_cost: float) -> bool:
    """The rule OBS-042 replaced, for the reference row."""
    if turnout_cost <= 0:
        return False
    options = sorted([*utilities, -voter.blank_threshold], reverse=True)
    return options[0] - options[1] < turnout_cost


def field_sizes() -> collections.Counter[int]:
    sizes: collections.Counter[int] = collections.Counter()
    with recording("_presidential_ballots", lambda args, kwargs, result: sizes.update([len(args[1])])):
        for seed in SEEDS:
            run_twin(twin_config(seed, YEARS))
    return sizes


def arm(setting: dict[str, float], cost: float, zero: tuple[Any, Any]) -> Arm:
    vote = {**setting, "turnout_cost": cost, "approval_party_carryover": CARRYOVER, "valence": 0.0}
    elections, choices = measure(vote)
    return utility_vote_arm(vote, elections, choices, zero[0], zero[1])


def row(label: str, a: Arm) -> str:
    cells = [f"{'✓' if fact.holds else '✗'} {fact.reading}" for fact in a.facts]
    return f"| {label} | " + " | ".join(cells) + f" | {'✓' if a.qualifies else '✗'} |"


def main() -> int:
    zero = measure(ZERO)
    lines = [
        "# OBS-042: the turnout cost under the best-against-blank rule", "",
        "Generated by `scripts/calibrate_turnout_rule.py`. Twin: as `calibrate_utility_vote.py` (full-mechanism "
        f"config, population 100, deterministic, seeds {SEEDS[0]}-{SEEDS[-1]}, {YEARS} years), party carryover "
        f"{CARRYOVER}. Not pre-registered; see the script's docstring.", "",
    ]
    sizes = field_sizes()
    lines += ["Candidates per presidential election attempt on the twin: "
              + ", ".join(f"{k}: {sizes[k]}" for k in sorted(sizes)) + ".", ""]
    chosen: dict[str, Arm | None] = {}
    for setting in SETTINGS:
        name = f"approval {setting['approval']}"
        header = [f"## {name}", ""]
        new_rule = simple_rules.abstains
        simple_rules.abstains = best_vs_next
        try:
            reference = arm(setting, 0.04, zero)
        finally:
            simple_rules.abstains = new_rule
        arms = [arm(setting, cost, zero) for cost in COSTS]
        chosen[name] = select(arms, utility_vote_choice)
        lines += header + ["| rule, cost | " + " | ".join(f.name for f in reference.facts) + " | all |",
                           "|---|" + "---|" * (len(reference.facts) + 1), row("best vs next, 0.04 (before)", reference)]
        lines += [row(f"best vs blank, {a.setting['turnout_cost']}", a) for a in arms] + [""]
        pick = chosen[name]
        lines += [f"Selected: {pick.setting['turnout_cost'] if pick else 'none qualifies'}.", ""]
        print(name, "->", pick.setting["turnout_cost"] if pick else None, flush=True)
    RESULTS.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
