"""The run explorer against real runs (run explorer F6): every run under the given roots
read through the API the Polity page uses, with each response's time and size.

Budgets, from the explorer's plan: a run's overview under 1.5 s cold and 50 ms once cached,
and a run's frames under 400 KB. Reads run directories only; writes nothing next to them.

Usage (from fast_api_voter/):
    python scripts/check_polity_explorer_real_runs.py p500=../../Vote-App-p500/fast_api_voter/scripts/seed_sweep_runs
"""
from __future__ import annotations

import logging
import os
import sys
import time
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

COLD_BUDGET_S = 1.5
CACHED_BUDGET_S = 0.05
FRAMES_BUDGET_KB = 400
RESULTS = Path(__file__).resolve().parent / "check_polity_explorer_real_runs_results.md"


def _timed(client: Any, path: str) -> tuple[Any, float]:
    start = time.perf_counter()
    response = client.get(path)
    return response, time.perf_counter() - start


def _run_rows(client: Any, run: dict[str, Any]) -> list[str]:
    base = f"/api/v2/polity/runs/{run['key']}"
    overview, cold = _timed(client, base)
    if overview.status_code != 200:
        return [f"| {run['relative_path']} | not explorable: {overview.json().get('detail')} | | | | |"]
    _, cached = _timed(client, base)
    body = overview.json()
    frame_bytes = 0
    partial = 0
    for start in range(0, body["last_tick"] + 1, 40):
        frames, _ = _timed(client, f"{base}/frames?from_tick={start}")
        frame_bytes += len(frames.content)
        partial += sum(frame["partial"] for frame in frames.json()["frames"])
    holders = sorted({term["holder"] for term in body["terms"]})
    biography_kb = max((len(_timed(client, f"{base}/citizens/{h}")[0].content) for h in holders), default=0) // 1024
    within = cold <= COLD_BUDGET_S and cached <= CACHED_BUDGET_S and frame_bytes // 1024 <= FRAMES_BUDGET_KB
    return [
        f"| {run['relative_path']} | {run['outcome'] or 'no digest'}, {body['last_tick'] + 1} ticks ({partial} partial) "
        f"| {cold:.2f} s / {cached * 1000:.0f} ms | {len(overview.content) // 1024} KB | {frame_bytes // 1024} KB "
        f"| {biography_kb} KB | {'yes' if within else '**no**'} |"
    ]


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__)
        return 2
    os.environ["POLITY_RUN_ROOTS"] = ",".join(argv)
    logging.disable(logging.CRITICAL)
    from fastapi.testclient import TestClient

    from api.core.config import get_settings
    from api.main import fastapi_app

    get_settings.cache_clear()
    client = TestClient(fastapi_app)
    listing, listed_in = _timed(client, "/api/v2/polity/runs")
    runs = listing.json()["runs"]
    lines = [
        "# The run explorer against real runs",
        "",
        "Generated by `scripts/check_polity_explorer_real_runs.py`, read-only. Budgets: overview "
        f"≤ {COLD_BUDGET_S} s cold and ≤ {CACHED_BUDGET_S * 1000:.0f} ms cached, frames ≤ {FRAMES_BUDGET_KB} KB for the whole run.",
        "",
        f"{len(runs)} runs listed in {listed_in:.2f} s.",
        "",
        "| run | outcome | overview cold / cached | overview | all frames | largest president biography | within budget |",
        "|---|---|---:|---:|---:|---:|---|",
    ]
    for run in runs:
        lines += _run_rows(client, run)
    RESULTS.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
