"""S1.3's precondition: does the pinned vLLM (ngram speculation on) honour
`thinking_token_budget`?

One thinking `vote_first_choice` case from the frozen bank is sent three times: no budget, a
256-token budget and a 64-token budget. Each call's reasoning tokens, finish reason and whether
its answer decodes as the case's batch are recorded through the call log.

**Honoured when**, written before the check runs:

- each budgeted call's reasoning tokens stay within its budget plus 16 tokens, the room for the
  forced reasoning-end string;
- each budgeted call's answer decodes;
- the unbudgeted call reasons past 256 tokens, so the smaller budgets actually bind.

Needs the vLLM server (GPU) and nothing else on it. Writes
check_thinking_token_budget_results.{md,json}.

Usage (from fast_api_voter/):
    python scripts/check_thinking_token_budget.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from api.domain.polity.bakeoff_bank import read_bank  # noqa: E402
from api.domain.polity.bakeoff_cases import resolve_max_tokens  # noqa: E402
from api.domain.polity.bakeoff_runner import decode_answers  # noqa: E402
from api.domain.polity.llm_call_log import CallLoggingClient, CallLogWriter, call_context, read_calls  # noqa: E402
from api.domain.polity.llm_client import LlmResponseError, build_json_client  # noqa: E402
from bakeoff_cases import DEFAULT_BANK, reference_config  # noqa: E402

BUDGETS: tuple[int | None, ...] = (None, 256, 64)
END_STRING_ROOM = 16
RESULTS = Path(__file__).resolve().parent / "check_thinking_token_budget_results"


def main() -> int:
    bank = read_bank(DEFAULT_BANK)
    case = next(c for c in bank.cases if c.family == "vote_first_choice" and c.think)
    config = reference_config()
    client = build_json_client(config.llm, seed=config.run.seed)
    log_path = RESULTS.with_suffix(".calls.jsonl")
    log_path.unlink(missing_ok=True)
    rows: list[dict[str, Any]] = []
    with CallLogWriter(log_path) as writer:
        logged = CallLoggingClient(client, writer, tick_source=lambda: None)
        for budget in BUDGETS:
            extra = {"thinking_token_budget": budget} if budget is not None else None
            decoded = True
            with call_context(kind="decision", decision_type=case.decision_type, unit_ids=case.unit_ids, attempt=0):
                try:
                    content = logged.complete_json(system_prompt=case.system_prompt, user_prompt=case.user_prompt,
                                                   json_schema=bank.schemas[case.decision_type],
                                                   max_tokens=resolve_max_tokens(case, client, config), think=True, extra_body=extra)
                    decode_answers(case, content)
                except LlmResponseError:
                    decoded = False
            rows.append({"budget": budget, "decoded": decoded})
    for row, call in zip(rows, [c for c in read_calls(log_path) if c.get("kind") == "decision"]):
        row.update(reasoning_tokens=call.get("reasoning_tokens"), finish_reason=call.get("finish_reason"))

    unbudgeted = rows[0]["reasoning_tokens"] or 0
    budgeted = rows[1:]
    within = all(r["reasoning_tokens"] is not None and r["reasoning_tokens"] <= r["budget"] + END_STRING_ROOM for r in budgeted)
    honoured = within and all(r["decoded"] for r in budgeted) and unbudgeted > 256
    lines = ["# Does the pinned vLLM honour thinking_token_budget? (S1.3)", "",
             f"Generated by `scripts/check_thinking_token_budget.py`, case `{case.case_id}` ({case.family}).", "",
             f"**{'Honoured' if honoured else 'Not shown to be honoured'}.**", "",
             "| budget | reasoning tokens | finish reason | answer decodes |", "|---|---:|---|---|"]
    lines += [f"| {r['budget'] or 'none'} | {r['reasoning_tokens']} | {r['finish_reason']} | {r['decoded']} |" for r in rows]
    RESULTS.with_suffix(".md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    RESULTS.with_suffix(".json").write_text(json.dumps({"case_id": case.case_id, "rows": rows, "honoured": honoured}, indent=2))
    print("\n".join(lines))
    return 0 if honoured else 1


if __name__ == "__main__":
    raise SystemExit(main())
