"""S1.1: where the p500 batch's time goes, per decision type and per election tick.

For each run directory given: the time attribution of the calls its journal kept (a resumed
run's superseded attempt dropped, see llm_time_attribution.kept_calls), each decision type's
share of the model time and of its own time in first attempts, retries, rejected answers,
truncations and budget probes, and the breakdown of every tick that held a presidential
election, inside and outside the model. Generated, not written by hand.

Usage (from fast_api_voter/):
    python scripts/p500_llm_time_report.py <run_dir> [<run_dir> ...] > scripts/p500_llm_time_results.md
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from api.domain.polity.llm_call_log import CALL_LOG_FILENAME, read_calls  # noqa: E402
from api.domain.polity.llm_time_attribution import CATEGORIES, attempts, attribute_run, by_tick, kept_calls  # noqa: E402
from attribute_llm_time import render_by_tick  # noqa: E402

SHARE_CATEGORIES = ("first_attempt", "retry", "rejected", "truncation", "budget_probe")


def _percent(part: float, whole: float) -> str:
    return f"{100 * part / whole:.1f}%" if whole else "–"


def run_section(run_dir: Path) -> list[str]:
    calls = read_calls(run_dir / CALL_LOG_FILENAME)
    report = attribute_run(run_dir)
    total = float(report["latency_seconds_sum"])
    lines = [f"## {run_dir.name}", "",
             f"{report['calls']} calls kept from {len(calls)} logged over {len(attempts(calls))} attempt(s); "
             f"model time {total:.0f} s (latency sum).", "",
             "| decision type | calls | model s | share of model time | " + " | ".join(SHARE_CATEGORIES) + " |",
             "|---|---:|---:|---:|" + "---:|" * len(SHARE_CATEGORIES)]
    by_type = report["by_decision_type"]
    decision_types = {name: buckets for name, buckets in by_type.items() if set(buckets) - {"warm_up"}}
    ordered = sorted(decision_types.items(), key=lambda item: -sum(bucket["seconds"] for bucket in item[1].values()))
    for decision_type, buckets in ordered:
        seconds = sum(bucket["seconds"] for bucket in buckets.values())
        calls_count = int(sum(bucket["calls"] for bucket in buckets.values()))
        shares = [_percent(buckets[c]["seconds"], seconds) if c in buckets else "–" for c in SHARE_CATEGORIES]
        lines.append(f"| {decision_type} | {calls_count} | {seconds:.0f} | {_percent(seconds, total)} | " + " | ".join(shares) + " |")
    other = {c: report["by_category"][c]["seconds"] for c in CATEGORIES if c not in SHARE_CATEGORIES and report["by_category"][c]["calls"]}
    if other:
        lines += ["", "Outside decision types: " + ", ".join(f"{c} {s:.0f} s" for c, s in other.items()) + "."]

    events = [json.loads(line) for line in (run_dir / "events.jsonl").read_text(encoding="utf-8").splitlines() if line.strip()]
    election_ticks = sorted({e["tick"] for e in events if e["event_type"] in ("elected", "election_no_winner", "election_invalidated")})
    rows = [row for row in by_tick(kept_calls(calls)) if row["tick"] in election_ticks]
    table = render_by_tick(rows, run_dir).splitlines()[2:]
    lines += ["", f"### Presidential election ticks ({', '.join(map(str, election_ticks))})", "", *table, ""]
    return lines


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("run_dirs", type=Path, nargs="+")
    args = parser.parse_args(argv)
    lines = ["# S1.1: where the p500 batch's time goes", "",
             "Generated by `scripts/p500_llm_time_report.py` from each run's `llm_calls.jsonl`. Seconds are call latencies; "
             "a tick's span runs from its first call's start to its last call's end, and its outside-model time is the "
             "span minus the time some call was in flight.", ""]
    for run_dir in args.run_dirs:
        lines += run_section(run_dir)
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
