"""add new attribute to vote and election

Revision ID: 370161dcf642
Revises: 81a2386bfa8e
Create Date: 2025-07-04 09:21:42.259811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370161dcf642'
down_revision = '81a2386bfa8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cast_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_column('cast_at')

    # ### end Alembic commands ###
