"""add participation_points to User

Revision ID: 517b84071cab
Revises: 864477aff6a3
Create Date: 2025-06-29 18:02:22.112832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517b84071cab'
down_revision = '864477aff6a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participation_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('participation_points')

    # ### end Alembic commands ###
