"""add party relationship to users

Revision ID: 864477aff6a3
Revises: d1c93dd3b024
Create Date: 2025-06-28 18:49:45.763766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864477aff6a3'
down_revision = 'd1c93dd3b024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('founded_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('party_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'parties', ['party_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('party_id')

    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_column('logo_url')
        batch_op.drop_column('founded_date')

    # ### end Alembic commands ###
