#!/usr/bin/env python3
"""Write docs/research/expert-review-packet.md, the packet for one social-choice researcher
(PLAN_BEYOND_CI W1.4): what we ask, how each verdict is checked, the criteria registry as
tables, and the works it cites. Everything is read from the repository, so the packet is
regenerated, never edited:

    python3 scripts/gen_review_packet.py

The registry (voter-app/src/data/method_criteria.json) stays the source of truth; the packet
is a dated snapshot of it to send.
"""

import hashlib
import json
import re
import unicodedata
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "voter-app/src/data/method_criteria.json"
BIB = ROOT / "docs/research/bibliography.bib"
EN = ROOT / "voter-app/src/i18n/locales/playground.en.ts"
OUT = ROOT / "docs/research/expert-review-packet.md"
REPO = "https://github.com/Burbanit0/Vote-App"

SYMBOL = {"yes": "✓", "no": "✗", "conditional": "◐"}
# Cells changed by the content fixes (W1.1, W1.2), which STATUS.md's open questions name.
ASKED = [("split_cycle", "participation"), ("random_ballot", "reversal"), ("majority_judgment", "majority")]
BASIS = {"engine-tested": "E", "literature": "L", "variant": "V"}


def en_block(opening: str) -> dict[str, str]:
    """`key: 'label',` lines of the first block in playground.en.ts that opens with `opening`."""
    lines = EN.read_text(encoding="utf-8").splitlines()
    start = next(i for i, line in enumerate(lines) if line.strip() == opening)
    indent = len(lines[start]) - len(lines[start].lstrip())
    out: dict[str, str] = {}
    for line in lines[start + 1:]:
        if line.strip() == "}," and len(line) - len(line.lstrip()) == indent:
            break
        m = re.match(r"\s*(\w+): '(.*)',$", line)
        if m:
            out[m.group(1)] = m.group(2).replace("\\'", "'")
    return out


def bib_entry(key: str) -> dict[str, str]:
    """One bibliography.bib entry's fields, one field per line as the file writes them."""
    text = BIB.read_text(encoding="utf-8")
    m = re.search(rf"@\w+\{{{re.escape(key)},\n(.*?)\n\}}", text, re.S)
    if not m:
        raise SystemExit(f"{key} is cited by the registry but not in {BIB.name}")
    fields = dict(re.findall(r"^\s*(\w+)\s*=\s*\{(.*)\},?$", m.group(1), re.M))
    return {k: latex_to_text(v) for k, v in fields.items()}


ACCENT = {"'": "\u0301", "`": "\u0300", '"': "\u0308", "^": "\u0302"}


def latex_to_text(value: str) -> str:
    """BibTeX's accents ({\\'e}) as Unicode, its page ranges (--) as an en dash, no braces."""
    value = re.sub(r"\{\\(['`\"^])(\w)\}", lambda m: unicodedata.normalize("NFC", m[2] + ACCENT[m[1]]), value)
    return value.replace("--", "–").replace("{", "").replace("}", "")


def cite(key: str) -> str:
    entry = bib_entry(key)
    surnames = [a.split(",")[0].strip() for a in entry["author"].split(" and ")]
    return f"{' & '.join(surnames)} ({entry['year']})"


def verdict_line(entry: dict[str, Any]) -> str:
    source = f", after {cite(entry['source'])}" if entry["source"] else ""
    note = f" {entry['note']}" if entry.get("note") else ""
    return f"{entry['verdict']}{source}.{note}"


def cell(entry: dict[str, Any]) -> str:
    basis = BASIS[entry["basis"]]
    unsourced = entry["basis"] == "literature" and not entry["source"]
    return f"{SYMBOL[entry['verdict']]} {basis}{'?' if unsourced else ''}"


def render() -> str:
    """The packet, from the registry, the bibliography and the English labels as they are now."""
    raw = REGISTRY.read_bytes()
    reg = json.loads(raw)
    rules: dict[str, dict[str, Any]] = reg["rules"]
    criteria: list[str] = reg["criteria"]
    rule_label = en_block("rules: {")
    crit_label = en_block("criteria: {")
    entries = [(r, c, e) for r, cells in rules.items() for c, e in cells.items()]
    count = {b: sum(1 for *_, e in entries if e["basis"] == b) for b in BASIS}
    sourced = sum(1 for *_, e in entries if e["basis"] == "literature" and e["source"])
    tested_criteria = [c for c in criteria if any(e["basis"] == "engine-tested" for r, cc, e in entries if cc == c)]
    tested_rules = sorted({r for r, _, e in entries if e["basis"] == "engine-tested"})
    sources = sorted({e["source"] for *_, e in entries if e["source"]})
    # A content hash, not a commit: CI's shallow checkout has no file history.
    registry_hash = hashlib.sha256(raw).hexdigest()[:12]

    def row_link(rule: str, crit: str) -> str:
        return f"{rule_label.get(rule, rule)} × {crit_label[crit]}"

    lines = [
        "# Expert review packet: Vote Lab's voting-criteria claims",
        "",
        "> Generated by `python3 scripts/gen_review_packet.py` from the criteria registry",
        f"> (`voter-app/src/data/method_criteria.json`, sha256 `{registry_hash}…`). Do not",
        "> edit it by hand: regenerate it, and regenerate it again before sending it.",
        "",
        "## What we ask",
        "",
        "Vote Lab is an open-source app that teaches how voting methods behave. For each of its",
        f"{len(rules)} methods it states whether the method satisfies {len(criteria)} classic criteria, "
        f"{len(entries)} verdicts in all.",
        "Each verdict rests on one of three bases (next section). We would be grateful for your",
        "review of three things:",
        "",
        f"1. **The {count['literature'] - sourced} literature verdicts that have no source yet** (marked `L?`"
        " below). Is each verdict right, and which work establishes it?",
        "2. **The cells we would most like a second opinion on**, set by earlier content fixes:",
        *[f"   - {row_link(r, c)}: {verdict_line(rules[r][c])}" for r, c in ASKED],
        f"   - The {count['variant']} variants (`V`, section 5): the textbook verdict, which this engine's own "
        "variant does not keep.",
        "3. **THEORY.md, sections 2 to 4** (methods, impossibility theorems, paradoxes; in French):",
        f"   [THEORY.md on the `polity` branch]({REPO}/blob/polity/THEORY.md#2-les-méthodes-de-vote).",
        "",
        "Any form of answer helps: a reply, comments in this file, or the app's \"report a content",
        f"error\" form ({REPO}/issues/new?template=content-error.yml), which every matrix cell",
        "links to with the cell already named.",
        "",
        "## 1. How each verdict is checked",
        "",
        f"- **Engine-tested (`E`, {count['engine-tested']} cells):** the {len(tested_rules)} ordinal methods × "
        f"{', '.join(crit_label[c] for c in tested_criteria)}. Both of the app's engines (TypeScript and Python) "
        "run property-based tests on random preference profiles:",
        "  - fast-check in `voter-app/src/lib/playgroundVoting.axioms.test.ts`, with 3 to 6 candidates and 3 to "
        "25 voters;",
        "  - Hypothesis in `fast_api_voter/api/tests/test_voting_criteria_matrix.py`, with 4 candidates.",
        "",
        "  A **no** is backed by a counterexample the tests find and assert. A **yes** means no "
        "counterexample was found: evidence, not a proof. A test fails if the registry disagrees "
        "with either engine.",
        f"- **Literature (`L`, {count['literature']} cells):** {sourced} cite a work that covers them exactly "
        f"({', '.join(cite(s) for s in sources)}). The other {count['literature'] - sourced} (`L?`) have no "
        "source yet: these are the ones this review is for.",
        f"- **Variant (`V`, {count['variant']} cells):** the textbook verdict, which this engine's own variant "
        "of the method does not keep. The note says how, and a test requires that the engine does depart "
        "from it.",
        "",
        "## 2. The matrix at a glance",
        "",
        "`✓` yes · `✗` no · `◐` conditional; `E` engine-tested, `L` literature with a source, `L?` "
        "literature without one, `V` variant.",
        "",
        "| Method | " + " | ".join(crit_label[c] for c in criteria) + " |",
        "|---|" + "---|" * len(criteria),
    ]
    for rule, cells in rules.items():
        lines.append(f"| {rule_label.get(rule, rule)} | " + " | ".join(cell(cells[c]) for c in criteria) + " |")
    lines += ["", "## 3. Every verdict, criterion by criterion", ""]
    for crit in criteria:
        lines += [f"### {crit_label[crit]}", "", "| Method | Verdict | Basis | Source | Note |", "|---|---|---|---|---|"]
        for rule, cells in rules.items():
            e = cells[crit]
            source = cite(e["source"]) if e["source"] else ("to be confirmed" if e["basis"] == "literature" else "")
            note = (e.get("note") or "").replace("|", "\\|")
            lines.append(f"| {rule_label.get(rule, rule)} | {e['verdict']} | {e['basis']} | {source} | {note} |")
        lines.append("")
    lines += ["## 4. Unsourced literature verdicts, by method", ""]
    for rule, cells in rules.items():
        missing = [crit_label[c] for c in criteria if cells[c]["basis"] == "literature" and not cells[c]["source"]]
        if missing:
            lines.append(f"- **{rule_label.get(rule, rule)}:** {', '.join(missing)}")
    lines += ["", "## 5. The variants", ""]
    for rule, crit, e in entries:
        if e["basis"] == "variant":
            lines.append(f"- **{row_link(rule, crit)}** ({e['verdict']}): {e.get('note', '')}")
    lines += ["", "## 6. Works cited", ""]
    for key in sources:
        b = bib_entry(key)
        where = ", ".join(x for x in (b.get("journal"), b.get("volume") and f"vol. {b['volume']}",
                                       b.get("number") and f"no. {b['number']}", b.get("pages") and f"pp. {b['pages']}") if x)
        lines.append(f"- {b['author']} ({b['year']}). *{b['title']}*. {where}. (`{key}`)")
    return "\n".join(lines) + "\n"


def main() -> None:
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
