/**
 * latexExport.ts — Academic LaTeX / BibTeX export for Vote Lab simulations.
 *
 * All exported documents are valid LaTeX that compile with pdflatex.
 * Special characters are escaped to avoid compilation errors.
 */
import { SimulationCompareResult } from '../types';
import { ScenarioConfig } from '../components/Simulation/simulationConstants';
import references, { MethodReference, toBibtex } from '../data/methodReferences';

// ── LaTeX special-character escaping ─────────────────────────────────────────

const LATEX_ESCAPE: [RegExp, string][] = [
  [/\\/g, '\\textbackslash{}'],
  [/&/g, '\\&'],
  [/%/g, '\\%'],
  [/\$/g, '\\$'],
  [/#/g, '\\#'],
  [/_/g, '\\_'],
  [/\{/g, '\\{'],
  [/\}/g, '\\}'],
  [/~/g, '\\textasciitilde{}'],
  [/\^/g, '\\textasciicircum{}'],
];

export function escapeLaTeX(text: string): string {
  // Apply in order: backslash first (to avoid double-escaping)
  return LATEX_ESCAPE.reduce((s, [re, rep]) => s.replace(re, rep), text);
}

// ── Derived helpers ───────────────────────────────────────────────────────────

function mostCommon(arr: (string | null)[]): string | null {
  const counts: Record<string, number> = {};
  for (const v of arr) {
    if (v) counts[v] = (counts[v] ?? 0) + 1;
  }
  const entries = Object.entries(counts);
  if (!entries.length) return null;
  return entries.sort((a, b) => b[1] - a[1])[0][0];
}

function avg(nums: (number | null | undefined)[]): number | null {
  const valid = nums.filter((n): n is number => n !== null && n !== undefined);
  return valid.length ? valid.reduce((a, b) => a + b, 0) / valid.length : null;
}

function fmtNum(n: number | null, decimals = 4): string {
  return n !== null ? n.toFixed(decimals) : '—';
}

// ── Per-method summary from multiple simulation runs ─────────────────────────

interface MethodSummary {
  methodKey: string;
  label: string;
  winner: string | null; // most common winner
  winCount: number; // how many runs this winner appeared in
  totalRuns: number;
  regret: number | null; // average bayesian_regret
  condorcet: boolean | null; // true/false/null if mixed
}

function buildMethodSummaries(
  results: SimulationCompareResult[],
  methodKeys: string[],
  methodLabels: Record<string, string>
): MethodSummary[] {
  return methodKeys.map((key) => {
    const winners = results.map((r) => r.methods[key]?.winner ?? null);
    const regrets = results.map((r) => r.methods[key]?.bayesian_regret);
    const condorcets = results.map((r) => r.methods[key]?.condorcet_consistent);
    const dominant = mostCommon(winners);
    const trueCount = condorcets.filter((v) => v === true).length;
    const falseCount = condorcets.filter((v) => v === false).length;
    const condorcetSummary =
      trueCount + falseCount === 0
        ? null
        : trueCount > falseCount
          ? true
          : falseCount > trueCount
            ? false
            : null;

    return {
      methodKey: key,
      label: methodLabels[key] ?? key,
      winner: dominant,
      winCount: dominant ? winners.filter((w) => w === dominant).length : 0,
      totalRuns: results.length,
      regret: avg(regrets),
      condorcet: condorcetSummary,
    };
  });
}

// ── 1. generateLatexTable ─────────────────────────────────────────────────────

export function generateLatexTable(
  results: SimulationCompareResult[],
  methodLabels: Record<string, string>,
  caption = 'Résultats de la simulation — Vote Lab'
): string {
  if (!results.length) return '% No simulation results available.\n';

  const methodKeys = Object.keys(results[0]?.methods ?? {});
  const summaries = buildMethodSummaries(results, methodKeys, methodLabels);

  const rows = summaries.map((s) => {
    const winnerStr = s.winner ? `${escapeLaTeX(s.winner)} (${s.winCount}/${s.totalRuns})` : '—';
    const condStr = s.condorcet === null ? '—' : s.condorcet ? 'Oui' : 'Non';
    const regretStr = fmtNum(s.regret, 4);
    return `    ${escapeLaTeX(s.label)} & ${winnerStr} & ${condStr} & ${regretStr} \\\\`;
  });

  return [
    '% Generated by Vote Lab — https://github.com/Burbanit0/Vote-App',
    '% Requires: \\usepackage{booktabs}',
    '',
    '\\begin{table}[htbp]',
    '  \\centering',
    `  \\caption{${escapeLaTeX(caption)}}`,
    '  \\label{tab:votelab-results}',
    '  \\begin{tabular}{llcr}',
    '    \\toprule',
    '    Méthode & Vainqueur dominant & Cohérence Condorcet & Regret bayésien moyen \\\\',
    '    \\midrule',
    ...rows,
    '    \\bottomrule',
    '  \\end{tabular}',
    '\\end{table}',
  ].join('\n');
}

// ── 2. generateBibtex ─────────────────────────────────────────────────────────

export interface SimulationExportParams {
  config: ScenarioConfig;
  numSimulations: number;
  methodCount: number;
  date: string; // ISO date string
  shareUrl?: string;
}

export function generateBibtex(params: SimulationExportParams): string {
  const { config, numSimulations, methodCount, date, shareUrl } = params;
  const year = new Date(date).getFullYear();
  const candidates = config.candidateInput
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
  const title = `Vote Lab Simulation: ${candidates.join(' vs ')}`;

  const fields = [
    `  author = {Vote Lab}`,
    `  title  = {${escapeLaTeX(title)}}`,
    `  year   = {${year}}`,
    `  note   = {Paramètres: ${config.numVoters.toLocaleString()} électeurs, ${candidates.length} candidats, ${methodCount} méthodes, ${numSimulations} simulation${numSimulations > 1 ? 's' : ''}}`,
    shareUrl ? `  url    = {${shareUrl}}` : null,
  ].filter(Boolean);

  return `@misc{votelab${year},\n${fields.join(',\n')}\n}`;
}

// ── 3. generateLatexReport ────────────────────────────────────────────────────

export function generateLatexReport(
  params: SimulationExportParams,
  results: SimulationCompareResult[],
  methodLabels: Record<string, string>
): string {
  if (!results.length) return '% No results to export.\n';

  const { config, numSimulations, date, shareUrl } = params;
  const year = new Date(date).getFullYear();
  const candidates = config.candidateInput
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
  const methodKeys = Object.keys(results[0]?.methods ?? {});
  const summaries = buildMethodSummaries(results, methodKeys, methodLabels);

  // Determine best method (lowest average regret)
  const byRegret = summaries
    .filter((s) => s.regret !== null)
    .sort((a, b) => (a.regret ?? 999) - (b.regret ?? 999));
  const bestMethod = byRegret[0];
  const condorcetWinner = results[0]?.condorcet_winner ?? null;

  // Collect references for methods used
  const usedRefs: MethodReference[] = [];
  const seenKeys = new Set<string>();
  for (const key of methodKeys) {
    const ref = references[key];
    if (ref && !seenKeys.has(ref.bibtexKey)) {
      usedRefs.push(ref);
      seenKeys.add(ref.bibtexKey);
    }
  }
  // Always include Arrow and Gibbard
  for (const extraKey of ['arrow1951', 'gibbard1973']) {
    const ref = (references as Record<string, MethodReference>)[extraKey];
    if (ref && !seenKeys.has(ref.bibtexKey)) {
      usedRefs.push(ref);
      seenKeys.add(ref.bibtexKey);
    }
  }

  // ── Table rows ──────────────────────────────────────────────────────────────
  const tableRows = summaries.map((s) => {
    const winStr = s.winner ? `${escapeLaTeX(s.winner)} (${s.winCount}/${s.totalRuns})` : '—';
    const condStr = s.condorcet === null ? '—' : s.condorcet ? 'Oui' : 'Non';
    const regretStr = fmtNum(s.regret, 4);
    const msData = results.map((r) => r.methods[s.methodKey]?.majority_satisfaction);
    const msStr = fmtNum(avg(msData), 3);
    return `    ${escapeLaTeX(s.label)} & ${winStr} & ${condStr} & ${regretStr} & ${msStr} \\\\`;
  });

  // ── Analysis paragraph ──────────────────────────────────────────────────────
  const analysisLines: string[] = [];
  if (bestMethod) {
    analysisLines.push(
      `La méthode présentant le regret bayésien moyen le plus faible est ` +
        `\\textbf{${escapeLaTeX(bestMethod.label)}} (${fmtNum(bestMethod.regret, 4)}), ` +
        `ce qui indique qu'elle génère le moins d'insatisfaction collective.`
    );
  }
  if (condorcetWinner) {
    const condMethod = summaries.find((s) => s.condorcet === true);
    analysisLines.push(
      `Le vainqueur de Condorcet identifié est \\textbf{${escapeLaTeX(condorcetWinner)}}.` +
        (condMethod
          ? ` La méthode ${escapeLaTeX(condMethod.label)} est cohérente avec ce critère.`
          : ' Certaines méthodes ne respectent pas ce critère.')
    );
  }
  analysisLines.push(
    `Ces résultats illustrent le théorème d'impossibilité d'Arrow~\\cite{arrow1951} : ` +
      `aucune méthode ne peut satisfaire simultanément tous les critères de justice ` +
      `avec trois candidats ou plus.`
  );

  // ── BibTeX entries ──────────────────────────────────────────────────────────
  const bibtexEntries = [...usedRefs.map(toBibtex), generateBibtex(params)].join('\n\n');

  const bibContent = bibtexEntries
    .split('\n')
    .map((l) => `% ${l}`)
    .join('\n');

  // ── Full document ───────────────────────────────────────────────────────────
  const lines = [
    '% ============================================================',
    '% Vote Lab — Rapport de simulation',
    `% Généré le ${date}`,
    '% Compiler with: pdflatex report.tex',
    '% ============================================================',
    '',
    '\\documentclass[a4paper,11pt]{article}',
    '',
    '\\usepackage[utf8]{inputenc}',
    '\\usepackage[T1]{fontenc}',
    '\\usepackage[french]{babel}',
    '\\usepackage{booktabs}',
    '\\usepackage{graphicx}',
    '\\usepackage[colorlinks=true,linkcolor=blue,citecolor=blue,urlcolor=blue]{hyperref}',
    '\\usepackage{amsmath}',
    '\\usepackage{geometry}',
    '\\geometry{margin=2.5cm}',
    '',
    '\\title{Vote Lab --- Rapport de simulation comparative\\\\',
    `  \\large ${escapeLaTeX(candidates.join(', '))}}`,
    `\\author{Vote Lab\\\\\\small\\url{${shareUrl ?? 'https://github.com/Burbanit0/Vote-App'}}}`,
    `\\date{${date}}`,
    '',
    '\\begin{document}',
    '',
    '\\maketitle',
    '',
    '\\section{Introduction}',
    '',
    `Ce rapport présente les résultats d'une simulation comparative de ${methodKeys.length} méthodes`,
    `de vote appliquées à un même électorat synthétique, généré par le modèle spatial de Vote Lab.`,
    `La simulation a été exécutée ${numSimulations} fois afin de mesurer la robustesse des résultats.`,
    `Les candidats sont : \\textbf{${escapeLaTeX(candidates.join(', '))}}.`,
    `L'ensemble des méthodes est comparé selon trois critères : le vainqueur élu,`,
    `la cohérence avec le critère de Condorcet, et le regret bayésien moyen~\\cite{votelab${year}}.`,
    '',
    '\\section{Paramètres de la simulation}',
    '',
    '\\begin{tabular}{ll}',
    '  \\toprule',
    '  Paramètre & Valeur \\\\',
    '  \\midrule',
    `  Candidats & ${escapeLaTeX(candidates.join(', '))} \\\\`,
    `  Électeurs par simulation & ${config.numVoters.toLocaleString()} \\\\`,
    `  Distribution idéologique & ${escapeLaTeX(config.ideology_distribution)} \\\\`,
    `  Nombre de simulations & ${numSimulations} \\\\`,
    `  Méthodes analysées & ${methodKeys.length} \\\\`,
    '  \\bottomrule',
    '\\end{tabular}',
    '',
    '\\section{Résultats comparatifs}',
    '',
    '\\begin{table}[htbp]',
    '  \\centering',
    '  \\caption{Résultats de la simulation par méthode de vote}',
    '  \\label{tab:results}',
    '  \\begin{tabular}{llcrc}',
    '    \\toprule',
    '    Méthode & Vainqueur & Condorcet & Regret bayésien & Satisfaction maj. \\\\',
    '    \\midrule',
    ...tableRows,
    '    \\bottomrule',
    '  \\end{tabular}',
    '  \\\\[0.3em]',
    '  \\small Vainqueur~: candidat le plus fréquent (n/N runs).  ',
    '  Regret bayésien~: plus bas = meilleur.',
    '\\end{table}',
    '',
    '\\section{Analyse}',
    '',
    ...analysisLines.map((l) => l + '\n'),
    '',
    '\\section*{Références}',
    '\\addcontentsline{toc}{section}{Références}',
    '',
    '% To compile with bibliography, save the BibTeX entries below',
    '% as references.bib and use \\bibliography{references}.',
    '% Below are the raw BibTeX entries for manual inclusion:',
    '',
    bibContent,
    '',
    '\\begin{thebibliography}{99}',
    ...usedRefs.map(
      (r) =>
        `\\bibitem{${r.bibtexKey}} ${escapeLaTeX(r.author)} (${r.year}). ` +
        `\\textit{${escapeLaTeX(r.title)}}. ` +
        (r.journal
          ? `\\textit{${escapeLaTeX(r.journal)}}` +
            (r.volume ? `, ${r.volume}` : '') +
            (r.pages ? `, pp.~${r.pages}` : '') +
            '.'
          : r.publisher
            ? `${escapeLaTeX(r.publisher)}.`
            : '.') +
        (r.doi ? ` \\doi{${r.doi}}` : '')
    ),
    `\\bibitem{votelab${year}} Vote Lab (${year}). ${escapeLaTeX(`Vote Lab Simulation: ${candidates.join(' vs ')}`)}. \\url{${shareUrl ?? 'https://github.com/Burbanit0/Vote-App'}}`,
    '\\end{thebibliography}',
    '',
    '\\end{document}',
  ];

  return lines.join('\n');
}

// ── 4. generateFullBibtex ─────────────────────────────────────────────────────
// Returns all method references as a single .bib file string

export function generateFullBibtex(methodKeys: string[], params: SimulationExportParams): string {
  const header = [
    '% Vote Lab — BibTeX references',
    `% Generated ${params.date}`,
    '% Include in your LaTeX project as references.bib',
    '',
  ].join('\n');

  const usedRefs: MethodReference[] = [];
  const seen = new Set<string>();
  for (const key of [...methodKeys, 'arrow1951', 'gibbard1973']) {
    const ref = (references as Record<string, MethodReference>)[key];
    if (ref && !seen.has(ref.bibtexKey)) {
      usedRefs.push(ref);
      seen.add(ref.bibtexKey);
    }
  }

  const simEntry = generateBibtex(params);

  return [header, ...usedRefs.map(toBibtex), simEntry].join('\n\n');
}

// ── Download helper ───────────────────────────────────────────────────────────

export function downloadText(content: string, filename: string, mimeType = 'text/plain'): void {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
